packages:
  - "."
  - "capacitor-plugins/*"

allowBuilds:
  '@applemusic-like-lyrics/core': true
  '@applemusic-like-lyrics/lyric': true
  '@applemusic-like-lyrics/react': true
  bufferutil: true
  cypress: true
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  register-scheme: true
  sharp: true
  utf-8-validate: true
